# Generated by Django 4.2.16 on 2024-10-27 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=125, verbose_name='title')),
                ('summary', models.TextField(verbose_name='summary')),
                ('date', models.DateField(verbose_name='date of publishing')),
                ('text', models.TextField(verbose_name='text')),
            ],
        ),
        migrations.DeleteModel(
            name='Catalog',
        ),
    ]
